# Generated by Django 4.2.5 on 2023-09-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("dateBefore", models.DateField()),
                ("dateAfter", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Load",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=30)),
                (
                    "trailerType",
                    models.CharField(
                        choices=[
                            ("FB", "Flatbed"),
                            ("DV", "Dry Van"),
                            ("RF", "Reefer"),
                            ("LB", "Lowboy"),
                            ("SD", "Stepdeck"),
                            ("OT", "Other"),
                            ("AN", "Any"),
                        ],
                        default="AN",
                        max_length=2,
                    ),
                ),
                ("weight", models.IntegerField()),
                ("volume", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Trailer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plates", models.CharField(max_length=6)),
                ("capacity", models.IntegerField()),
                ("pickup", models.CharField(max_length=50)),
                ("dropoff", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AV", "Available"),
                            ("IT", "In Transit"),
                            ("UN", "Unavailable"),
                        ],
                        default="AV",
                        max_length=2,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FB", "Flatbed"),
                            ("DV", "Dry Van"),
                            ("RF", "Reefer"),
                            ("LB", "Lowboy"),
                            ("SD", "Stepdeck"),
                            ("OT", "Other"),
                            ("AN", "Any"),
                        ],
                        default="AN",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DE", "Delivered"),
                            ("IP", "In Progress"),
                            ("TA", "To Assign"),
                            ("CA", "Cancelled"),
                        ],
                        default="TA",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=10)),
                (
                    "userType",
                    models.CharField(
                        choices=[
                            ("LO", "LoadOwner"),
                            ("DR", "Driver"),
                            ("TO", "TrailerOwner"),
                        ],
                        default="LO",
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
