# Generated by Django 4.2.5 on 2023-09-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesspoint", name="dateAfter", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="accesspoint", name="dateBefore", field=models.DateTimeField(),
        ),
    ]
