# Generated by Django 4.2.5 on 2023-09-26 02:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_accesspoint_dateafter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="dropoff",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dropoff",
                to="api.accesspoint",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="load",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="api.load"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="loadOwner",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="pickup",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pickup",
                to="api.accesspoint",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="trailer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.trailer",
            ),
        ),
        migrations.AlterField(
            model_name="accesspoint",
            name="dateAfter",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 25, 21, 40, 26, 426604)
            ),
        ),
        migrations.AlterField(
            model_name="accesspoint",
            name="dateBefore",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 25, 21, 40, 26, 426604)
            ),
        ),
    ]
