# Generated by Django 4.2.5 on 2023-09-26 02:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_trip_dropoff_trip_load_trip_loadowner_trip_pickup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trailer",
            name="driver",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="trailer",
            name="owner",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to="api.user",
            ),
        ),
        migrations.AlterField(
            model_name="accesspoint",
            name="dateAfter",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 25, 21, 47, 11, 407397)
            ),
        ),
        migrations.AlterField(
            model_name="accesspoint",
            name="dateBefore",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 25, 21, 47, 11, 407397)
            ),
        ),
    ]
