# Generated by Django 4.2.5 on 2023-09-26 03:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_trailer_driver_trailer_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="trailer", name="owner",),
        migrations.AlterField(
            model_name="accesspoint",
            name="dateAfter",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 25, 22, 5, 41, 964147)
            ),
        ),
        migrations.AlterField(
            model_name="accesspoint",
            name="dateBefore",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 25, 22, 5, 41, 964147)
            ),
        ),
        migrations.AlterField(
            model_name="trailer",
            name="driver",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
    ]
