# Generated by Django 4.2.5 on 2023-09-26 03:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_trailer_owner_alter_accesspoint_dateafter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesspoint",
            name="dateAfter",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 25, 22, 6, 19, 242938)
            ),
        ),
        migrations.AlterField(
            model_name="accesspoint",
            name="dateBefore",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 25, 22, 6, 19, 242938)
            ),
        ),
        migrations.AlterField(
            model_name="trailer",
            name="driver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="TrailerAssigned",
                to="api.user",
            ),
        ),
    ]
