# Generated by Django 4.2.5 on 2023-09-27 01:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_remove_accesspoint_dateafter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesspoint",
            name="after",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 26, 20, 15, 23, 819702)
            ),
        ),
        migrations.AlterField(
            model_name="accesspoint",
            name="before",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 26, 20, 15, 23, 819702)
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="dropoff",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dropoff",
                to="api.accesspoint",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="load",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="api.load"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="pickup",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pickup",
                to="api.accesspoint",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="trailer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.trailer",
            ),
        ),
    ]
