# Generated by Django 4.2.5 on 2023-09-27 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_accesspoint_after_alter_accesspoint_before_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesspoint",
            name="after",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 27, 18, 30, 13, 243391)
            ),
        ),
        migrations.AlterField(
            model_name="accesspoint",
            name="before",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 27, 18, 30, 13, 243391)
            ),
        ),
    ]
