# Generated by Django 4.2.5 on 2023-09-28 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_accesspoint_after_alter_accesspoint_before"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesspoint",
            name="after",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 27, 20, 11, 38, 115913)
            ),
        ),
        migrations.AlterField(
            model_name="accesspoint",
            name="before",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 27, 20, 11, 38, 115913)
            ),
        ),
    ]
