# Generated by Django 4.2.5 on 2023-10-03 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_alter_accesspoint_after_alter_accesspoint_before"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesspoint",
            name="after",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 2, 20, 30, 37, 636871)
            ),
        ),
        migrations.AlterField(
            model_name="accesspoint",
            name="before",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 2, 20, 30, 37, 636871)
            ),
        ),
    ]
