# Generated by Django 4.2.5 on 2023-11-03 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_accesspoint_after_alter_accesspoint_before_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='after',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 18, 18, 15, 715989)),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='before',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 18, 18, 15, 715981)),
        ),
    ]
