# Generated by Django 4.2.5 on 2023-11-30 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_errorlogs_trailer_isavailable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesspoint",
            name="after",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 30, 18, 38, 13, 489157)
            ),
        ),
        migrations.AlterField(
            model_name="accesspoint",
            name="before",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 30, 18, 38, 13, 489157)
            ),
        ),
    ]
